# Generated by Django 3.0.5 on 2020-04-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='pics/DJI_0329.jpg', upload_to='pics'),
        ),
    ]
