# Generated by Django 3.0.5 on 2020-04-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200414_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='starttext',
            field=models.CharField(default='Learn more', max_length=25),
            preserve_default=False,
        ),
    ]
