# Generated by Django 3.0.5 on 2020-04-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='experience',
        ),
    ]
