# Generated by Django 3.0.5 on 2020-04-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_locgallery'),
        ('experience', '0002_auto_20200415_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='details',
            field=models.CharField(default='default details', max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='galleryimg',
            field=models.ImageField(default='DJI_0329', upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='img',
            field=models.ImageField(default='DJI_0329', upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.ManyToManyField(to='locations.location'),
        ),
        migrations.AddField(
            model_name='experience',
            name='slug',
            field=models.SlugField(default='experience', unique=True),
            preserve_default=False,
        ),
    ]
