# Generated by Django 3.0.5 on 2020-04-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_auto_20200415_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='price',
            field=models.IntegerField(default='100'),
            preserve_default=False,
        ),
    ]
