# Generated by Django 3.0.5 on 2020-04-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_experience_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='img',
            field=models.ImageField(default='DJI_0329', upload_to='pics'),
            preserve_default=False,
        ),
    ]
