# Generated by Django 3.0.5 on 2020-04-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0006_cat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='slug',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
