# Generated by Django 3.0.5 on 2020-04-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='desc2',
            field=models.TextField(default='default'),
        ),
    ]
