# Generated by Django 3.0.5 on 2020-04-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_desc2'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
