# Generated by Django 3.0.5 on 2020-05-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_locgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='pics')),
                ('slug', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='locgallery',
        ),
    ]
