# Generated by Django 3.0.5 on 2020-05-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20200512_0154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cat',
            new_name='category',
        ),
        migrations.AddField(
            model_name='location',
            name='category',
            field=models.ManyToManyField(to='locations.category'),
        ),
    ]
