# Generated by Django 3.0.5 on 2020-05-11 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20200512_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='locgallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('galleryname', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='locations.location')),
            ],
        ),
    ]
