# Generated by Django 3.0.5 on 2020-05-11 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_locgallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='locgallery',
        ),
    ]
