# Generated by Django 3.0.5 on 2020-04-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0004_locgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('img', models.ImageField(upload_to='pics')),
                ('type', models.CharField(choices=[('Coaster', 'coaster'), ('SUV', 'suv'), ('Jeep', 'jeep'), ('Saloon', 'minivan'), ('Luxury', 'luxuryy')], default='saloon', max_length=15)),
                ('numpeople', models.IntegerField()),
                ('price', models.IntegerField()),
                ('location', models.ManyToManyField(to='locations.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
