# Generated by Django 3.0.5 on 2020-04-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20200418_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='ac',
            field=models.BooleanField(default=True),
        ),
    ]
