# Generated by Django 3.0.5 on 2020-05-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_transport_ac'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='desc',
            field=models.TextField(default='description for toyota corolla', max_length=300),
            preserve_default=False,
        ),
    ]
