# Generated by Django 3.0.5 on 2020-05-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_transport_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='mileage',
            field=models.FloatField(default=8),
            preserve_default=False,
        ),
    ]
