# Generated by Django 3.0.5 on 2020-05-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_transport_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='rules',
            field=models.TextField(default='driver food and stays are not included', max_length=800),
            preserve_default=False,
        ),
    ]
