# Generated by Django 3.0.5 on 2020-05-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_transport_offroad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('datebooked', models.DateTimeField(auto_now=True)),
                ('numdays', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['startdate'],
            },
        ),
    ]
