# Generated by Django 3.0.5 on 2020-05-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_transportbooking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportbooking',
            options={},
        ),
        migrations.RemoveField(
            model_name='transportbooking',
            name='datebooked',
        ),
        migrations.AlterField(
            model_name='transportbooking',
            name='startdate',
            field=models.CharField(max_length=100),
        ),
    ]
