# Generated by Django 3.0.5 on 2020-05-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_auto_20200507_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportbooking',
            name='startdate',
            field=models.DateTimeField(),
        ),
    ]
