# Generated by Django 3.0.5 on 2020-05-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_auto_20200507_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportbooking',
            name='startdate',
            field=models.DateField(),
        ),
    ]
