# Generated by Django 3.0.5 on 2020-05-07 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_auto_20200507_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportbooking',
            name='transport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transport.transport'),
            preserve_default=False,
        ),
    ]
