# Generated by Django 3.0.5 on 2020-05-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0013_transportbooking_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportbooking',
            name='transport',
            field=models.IntegerField(),
        ),
    ]
